---
# tasks file for mmv-ru.vim

- name: Vim installed
  package:
    name:
      - vim
    state: present
  tags: [configuration, vim, vim-install]

- name: Vim-enhanced (for RedHat)
  package:
    name:
      - vim-enhanced # TODO: vim-enhanced ok after vim. It included or just preinstalled?
    state: present
  when: ansible_os_family == "RedHat"
  tags: [configuration, vim, vim-install, redhat]

- name: Stat vimrc
  stat: path={{ ansible_env.HOME }}/.vimrc
  register: vimrc
  tags: [configuration, vim, vim-install]

- name: Write vimrc
  copy: src=vimrc dest={{ ansible_env.HOME }}/.vimrc mode=0644
  when: not vimrc.stat.exists
  tags: [configuration, vim, vim-install]

- name: fix vimrc for Archlinux/Manjaro
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.vimrc"
    marker: '" {mark} ANSIBLE MANAGED BLOCK'
    block: |
      " Uncomment the following to have Vim jump to the last position when
      " reopening a file
      if has("autocmd")
        au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
      endif
  when: ansible_os_family == "Archlinux"
  tags: [configuration, vim, vim-install, redhat]

